### ISSUE TITLE
최근 들어서 도서관 이용 종료 알림 작동이 잘 안되는 것 같습니다.

### ISSUE THREAD

**Issue by GooDongWoo** [lewisleedev/koala#17]
최근 들어 도서관 이용 종료 알림이 작동을 하지 않고 그냥 종료시간이 넘어버리거나
종료시간이 몇시간이 넘어서 도서관 이용을 하지 않는데 곧 종료된다고 알람이 울리는 등 
알람 기능이 제대로 작동하지 않는 것 같습니다.

처음 사용할 때는 알람이 잘 작동되었던 것으로 기억하는데

경희대 API가 바뀌거나 한 것 같습니다.

**Comment by shlewislee** [comment]
이용 종료 알림은 API와 무관하게 좌석 예약 후 3시간 30분 후에 울리도록, 그리고 좌석 퇴실 시 취소되도록 만들어져있습니다.

앱에서 예약/퇴실을 해야만 알람이 울리고 취소가됩니다.

설명하신 증상은 배터리 최적화 등등의 이유로 발생하는 증상입니다. 앱이 업데이트가 된게 없기때문에 기기 또는 OS 문제로 보입니다. Koala 앱의 배터리 최적화를 꺼보시는걸 추천드립니다. 그래도 안되면 이 페이지를 참고해보세요:

https://dontkillmyapp.com

그럼에도 문제가 발생하면 남겨주세요.

**Comment by GooDongWoo** [comment]
"설명하신 증상은 배터리 최적화 등등의 이유로 발생하는 증상입니다"
혹시나 했는데 앱 확인해보니 배터리 최적화 설정이 되어있네요.
제한없음으로 설정했습니다.

빠른 피드백 감사합니다.
